<a href="https://colab.research.google.com/github/22f2000792/MLP-prac/blob/main/Copy_of_Practice_Oppe_2_(extended_version_with_updated_syllabus_content).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Dataset Description

Use the following dataset for Part1: [dataset](https://drive.google.com/file/d/1cHGfVASFltupF3uLF3LoYXiwftoLpk3u/view?usp=sharing)

***Download the dataset in your machine, then upload it in colab.***

Following is description of different columns in the dataset.

1. `CRIM`: per capita crime rate in the vicinity

2. `ZN`: amount of residential land reserved in the vicinity.

3. `INDUS`: proportion of industrial land reserved  nearby (in square kilometers)

4. `RIVERSIDE`: If the boundary faces river side (= 1 if tract bounds river; 0 otherwise)

5. `POLINDEX`: polution index

6. `RM`: number of rooms in the house.

7. `AGE`: Age of the property in years.

8. `DIS`: weighted distances to the major economic centres (in kilometers)

9. `HIGHWAYCOUNT`: Number of highways within 5 KM of distance.

10. `TAX`: full-value property-tax rate per 1 lac.

11. `PTRATIO`: student-teacher ratio in the vicinity.

12. `IMM`: Immigration index in the vicinity.

13. `BPL`: % of below poverty line population in the vicinity.

14. `PRICE`: Price of the home in lacs, this is the target column.

# Part 1: Data preprocessing

### **Note**: For numerical type questions, always enter the answer correct upto 3 decimal places without rounding off, unless otherwise stated.

##Q1. [1 marks][MCQ] Which dataset are you using for this exam?

Options:

A) V1

B) V2

C) V3

D) V4

E) V5

Answer: E

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd
import numpy as np
path='/content/drive/MyDrive/Dataset/V1.csv'
df=pd.read_csv(path)
df.head(3)

,CRIM,ZN,INDUS,POLINDEX,RM,AGE,DIS,HIGHWAYCOUNT,TAX,PTRATIO,IMM,BPL,PRICE,RIVERSIDE
0,1.026769,1.429034,7.851300,1.134216,6.0,42.0,5.251911,5,279.201277,20.689586,398.811960,10.461456,22.991633,NO
1,0.848089,0.255543,6.263434,1.245993,7.0,63.0,4.305546,8,307.444529,17.465398,377.153649,11.619690,24.551055,NO
2,10.925905,0.441022,18.322960,2.824833,8.0,-2.0,2.409495,25,666.492973,20.351601,387.061355,19.366070,15.875346,NO

## Q.2 [2 marks][MCQ] How many samples are there in the dataset?

Options:

A) 4000

B) 5000

C) 6000

D) 7000

Ans: A

In [4]:
# Solution
df.shape

(4000, 14)

## Q.3 [2 marks][NAT] What is the average house price (in lacs)?


Ans: 24.355 [Range 24.30 to 24.40]

In [5]:
# Solution
df.PRICE.mean()

np.float64(24.355923220694248)

## Q.4 [3 marks][MCQ] How many houses have 5 or more rooms?

Options:

A) 3953

B) 3921

C) 3896

D) 3932

E) 3925

F) None of these

ANS: A

In [6]:
# Solution
df[df['RM']>=5].shape

(3953, 14)

## Q.5 [3 marks][NAT] What is the average price of the top 10 most expensive houses (in lacs)?

Ans: 52.365

[Range: 52.31 to 52.41]

In [7]:
# Solution
df.PRICE.sort_values(ascending=False).head(10).mean()

np.float64(52.36590175716407)

## Q.6 [2 marks][MCQ] What is the total number of missing or unknown values in the number of rooms feature?

(Hint: carefully look at the values the feature takes and find out implausible value.)

Options:

A) 40

B) 71

C) 99

D) 61

E) 68

F) None of these

Ans: A

In [8]:
# Solution
(df['RM']<=0).sum()
# or df[df['RM']<=0].shape

np.int64(40)

## Q.7 [2 marks][MCQ] What is the total number of missing or unknown values in the age feature?

(Hint: carefully look at the values the feature takes and find out implausible value.)

Options:

A) 50

B) 83

C) 74

D) 64

E) 59

F) None of these

Ans: A

In [9]:
df[df['AGE']<0].shape

(50, 14)

## Q.8 [2 marks][MCQ] What is the total number of missing or unknown values in the `RIVERSIDE` feature?

(Hint: carefully look at the values the feature takes and find out implausible value.)

Options:

A) 88

B) 101

C) 56

D) 62

E) 80

F) None of these

Ans: A

In [10]:
# Solution
df.RIVERSIDE.unique()

array(['NO', 'UNKNOWN', 'YES'], dtype=object)

In [11]:
(df.RIVERSIDE=='UNKNOWN').sum()

np.int64(88)

In [12]:
# Solution

## Q.9 [3 marks][MCQ] How many houses are on riverside and were built within last 50 years (i.e. a house 50 years old or younger)? For this question, ignore the rows that have missing values in either riverside feature or age feature.

Options:

A) 44

B) 42

C) 52

D) 43

E) 37

F) None of these

Ans: A

In [13]:
# Solution

df[(df['RIVERSIDE'] == 'YES') & (df['AGE'] <= 50) & (df['AGE'] > 0)].shape[0]

44

## Q.10 [3 marks][MCQ] How many houses are near to exactly 6, 7 or 8 highways (all three inclusive)?

Options:

A) 1211

B) 1174

C) 1234

D) 938

E) 1209

F) None of these

Ans: A

In [14]:
# Solution
df[(df['HIGHWAYCOUNT']==6) |(df['HIGHWAYCOUNT']==7) |(df['HIGHWAYCOUNT']==8)].shape

(1211, 14)

## Q.11 [4 marks][MCQ] Create a column 'CATEGORY' and divide the houses in categories as following:

- Category 1: house price <10 lacs
- Category 2: 10 lacs <= house price <20 lacs
- Category 3: 20 lacs <= house price <30 lacs
- Category 4: 30 lacs <= house price <40 lacs
- Category 5: house price >=40 lacs


Which category has the highest number of records?

Options:

A) 1

B) 2

C) 3

D) 4

E) 5

F) There is a tie between multiple categories

Ans: C

In [15]:
# Solution
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CRIM          4000 non-null   float64
 1   ZN            4000 non-null   float64
 2   INDUS         4000 non-null   float64
 3   POLINDEX      4000 non-null   float64
 4   RM            4000 non-null   float64
 5   AGE           4000 non-null   float64
 6   DIS           4000 non-null   float64
 7   HIGHWAYCOUNT  4000 non-null   int64
 8   TAX           4000 non-null   float64
 9   PTRATIO       4000 non-null   float64
 10  IMM           4000 non-null   float64
 11  BPL           4000 non-null   float64
 12  PRICE         4000 non-null   float64
 13  RIVERSIDE     4000 non-null   object
dtypes: float64(12), int64(1), object(1)
memory usage: 437.6+ KB

In [16]:
def get_category_with_map(price):
    if price < 10:
        return 'cat1'
    elif 10 <= price < 20:
        return 'cat2'
    elif 20 <= price < 30:
        return 'cat3'
    elif 30 <= price < 40:
        return 'cat4'
    else: # price >= 40
        return 'cat5'

df['Category'] = df['PRICE'].map(get_category_with_map)

In [17]:
df['Category'].unique()

array(['cat3', 'cat2', 'cat5', 'cat4', 'cat1'], dtype=object)

# Apply Pre processing

## Divide the data into training and test sets
- Replace the respective missing or unknown values in features room count, riverside and age with `np.nan`.
- Keep 30% of the data as test set.
- Use random_state as 0
- `PRICE` is the target, rest of the columns are the features.
<!-- - In 'RIVERSIDE' feature, replace 'NO' with 0 and 'YES' with 1. -->
- Apply train test split.

**Hint**: look for the documentation of the usual function that divides the data into training and test datasets.

In [18]:
# Solution
df['RM'].unique()

array([ 6.,  7.,  8.,  9., 10., -1.,  5.,  4., 11.])

In [19]:
df['RM']=df['RM'].replace(-1,np.nan)
df['RM'].unique()

array([ 6.,  7.,  8.,  9., 10., nan,  5.,  4., 11.])

In [20]:
df['RIVERSIDE'].unique()

array(['NO', 'UNKNOWN', 'YES'], dtype=object)

In [21]:
df['RIVERSIDE']=df['RIVERSIDE'].replace('UNKNOWN',np.nan)
df['RIVERSIDE'].unique()

array(['NO', nan, 'YES'], dtype=object)

In [22]:
df['AGE'].unique()

array([ 42.,  63.,  -2.,   9.,  20.,  95.,  35.,  97.,  36.,  78.,  99.,
        96.,  19.,  73.,  86.,  37.,  76.,  50.,  32.,  92., 101.,   8.,
        94.,  84.,  47.,  43.,  65.,  46.,  59.,  74.,  93.,  80.,  98.,
       102.,  56., 100.,  89.,  53.,  18.,  71.,  62.,  83.,  66.,   7.,
        77.,  91.,  90.,  58.,  57.,  60.,  87.,  75.,  34.,  85.,  48.,
        33.,  38.,  30.,  23.,  55.,  11.,  14.,  45.,  41.,  88.,  16.,
        12.,  79.,  67.,  39.,  49.,  61.,  70.,  54.,  10.,  22.,  72.,
        15.,  51.,  81.,  31.,  52.,  44.,  28.,  17.,  40.,  29.,  69.,
        64.,  24.,  82.,  26.,  68.,  27.,  13., 103.,  21.,  25.,   6.,
         5.,   3.,   4.])

In [23]:
df['AGE']=df['AGE'].replace(-2,np.nan)
(df['AGE']<0).sum()

np.int64(0)

In [24]:
## df.loc[df['AGE'] < 5, 'AGE'] = np.nan
# replacing value less than 5

In [25]:
# another way
# df['AGE'] = df['AGE'].apply(lambda x: np.nan if x < 5 else x)

In [26]:
# Using map for the same operation
#df['AGE'] = df['AGE'].map(lambda x: np.nan if x < 5 else x)
#display(df['AGE'].head()) # Display the effect of the change

## Q.12 [2 marks][MCQ] What is the number of samples in the training set?

Options:

A) 2800

B) 2900

C) 3000

D) 3100

Ans: A

In [27]:
from sklearn.model_selection import train_test_split
feature=df.drop('PRICE',axis=1)
target=df['PRICE'].copy()
X_train,X_test,y_train,y_test=train_test_split(feature,target,random_state=0,test_size=0.3)
print(X_train.shape)

(2800, 14)

### Apply following preprocessing steps:


- Drop `CATEGORY` column
- `CRIM`: min max scaling
- `ZN`: min max scaling
- `INDUS`: standard scaling
- `POLINDEX`: min max scaling
- `DIS`: min max scaling
- `HIGHWAYCOUNT`: min max scaling
- `TAX`: min max scaling
- `PTRATIO`: min max scaling
- `IMM`: min max scaling
- `BPL`: min max scaling
- `RM`: impute with median then min max scaling
- `AGE`: impute with mean then min max scaling
- `RIVERSIDE`: Impute with most frequent value then one hot encode.

NOTE:
1. Make sure to preprocess the features in the above order exactly. Answer of Q.16 depends upon correct order of featuring processing.
2. You may have to use multiple instances of a trasnformer for this question.

In [28]:
X_train.head(2)

,CRIM,ZN,INDUS,POLINDEX,RM,AGE,DIS,HIGHWAYCOUNT,TAX,PTRATIO,IMM,BPL,RIVERSIDE,Category
3336,2.419091,0.463975,9.464205,0.532043,7.0,89.0,2.728780,6,384.198987,21.935086,396.354281,16.23860,NO,cat2
2540,0.488829,20.571280,7.478404,1.016154,8.0,NaN,4.586203,4,223.493157,20.379584,391.076562,6.77379,YES,cat4

In [29]:
X_train=X_train.drop('Category',axis=1)
X_test=X_test.drop('Category',axis=1)
X_train.head(2)

,CRIM,ZN,INDUS,POLINDEX,RM,AGE,DIS,HIGHWAYCOUNT,TAX,PTRATIO,IMM,BPL,RIVERSIDE
3336,2.419091,0.463975,9.464205,0.532043,7.0,89.0,2.728780,6,384.198987,21.935086,396.354281,16.23860,NO
2540,0.488829,20.571280,7.478404,1.016154,8.0,NaN,4.586203,4,223.493157,20.379584,391.076562,6.77379,YES

In [30]:
np.var(X_train['CRIM']),np.var(X_test['CRIM'])

(6.030796138055849, 6.347974600393075)

In [31]:
from sklearn.preprocessing import MinMaxScaler
mm=MinMaxScaler()
X_train['CRIM']=mm.fit_transform(X_train[['CRIM']])
X_test['CRIM']=mm.transform(X_test[['CRIM']])
print(np.var(X_train['CRIM']))
print(np.var(X_test['CRIM']))

0.03805744560021884
0.040059005891701666

In [32]:
for i in X_train.select_dtypes(include=np.float64):
    print(f'{i} var {np.var(X_train[i])}')

CRIM var 0.03805744560021884
ZN var 552.9654453111748
INDUS var 46.855000391878804
POLINDEX var 0.36836364924859333
RM var 0.891251547654738
AGE var 797.3046136377578
DIS var 4.7642380918797125
TAX var 22785.780292545933
PTRATIO var 5.2037986180561395
IMM var 4270.58928485137
BPL var 37.28375248257752

In [33]:
for i in X_test.select_dtypes(include=np.float64):
    print(f'{i} var {np.var(X_test[i])}')

CRIM var 0.040059005891701666
ZN var 520.6042983991712
INDUS var 45.933623976553235
POLINDEX var 0.3440157002835788
RM var 0.8983857072240643
AGE var 799.6598214184494
DIS var 4.6399211996375325
TAX var 22069.86546625656
PTRATIO var 4.988866893566837
IMM var 5296.0067984352745
BPL var 38.7632921635547

In [34]:
X_train[['ZN','POLINDEX','DIS','HIGHWAYCOUNT','TAX','PTRATIO','IMM','BPL']]=mm.fit_transform(X_train[['ZN','POLINDEX','DIS','HIGHWAYCOUNT','TAX','PTRATIO','IMM','BPL']])
X_test[['ZN','POLINDEX','DIS','HIGHWAYCOUNT','TAX','PTRATIO','IMM','BPL']]=mm.transform(X_test[['ZN','POLINDEX','DIS','HIGHWAYCOUNT','TAX','PTRATIO','IMM','BPL']])

In [35]:
for i in X_train.select_dtypes(include=np.float64):
    print(f'{i} var {np.var(X_train[i])}')

CRIM var 0.03805744560021884
ZN var 0.053494413548247126
INDUS var 46.855000391878804
POLINDEX var 0.026174011030067307
RM var 0.891251547654738
AGE var 797.3046136377578
DIS var 0.03005007674708354
HIGHWAYCOUNT var 0.08212561209394882
TAX var 0.08235451361310316
PTRATIO var 0.04144727314454568
IMM var 0.0267015488804112
BPL var 0.03223154859810897

In [36]:
for i in X_test.select_dtypes(include=np.float64):
    print(f'{i} var {np.var(X_test[i])}')

CRIM var 0.040059005891701666
ZN var 0.05036376480611445
INDUS var 45.933623976553235
POLINDEX var 0.024443972015442
RM var 0.8983857072240643
AGE var 799.6598214184494
DIS var 0.029265957213006562
HIGHWAYCOUNT var 0.08273323060486493
TAX var 0.07976698680688923
PTRATIO var 0.03973538255342503
IMM var 0.03311289729991697
BPL var 0.03351060051630135

In [37]:
np.var(X_train['INDUS']),np.var(X_test['INDUS'])

(46.855000391878804, 45.933623976553235)

In [38]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train['INDUS']=scaler.fit_transform(X_train[['INDUS']])
X_test['INDUS']=scaler.transform(X_test[['INDUS']])
print(np.var(X_train['INDUS']))
print(np.var(X_test['INDUS']))

1.0000000000000029
0.9803355798181751

In [39]:
print(X_train['RM'].isna().sum(),np.var(X_train['RM']))
print(X_test['RM'].isna().sum(),np.var(X_test['RM']))

30 0.891251547654738
10 0.8983857072240643

In [40]:
median_train=X_train['RM'].median()
median_test=X_test['RM'].median()
X_train['RM']=X_train['RM'].fillna(median_train)
X_test['RM']=X_test['RM'].fillna(median_test)
print(X_train['RM'].isna().sum())
print(X_test['RM'].isna().sum())

0
0

In [41]:
X_train['RM']=mm.fit_transform(X_train[['RM']])
X_test['RM']=mm.transform(X_test[['RM']])
print(np.var(X_train['RM']))
print(np.var(X_test['RM']))

0.01799808413161201
0.01818316326530614

In [42]:
print(X_train['AGE'].isna().sum(),np.var(X_train['AGE']),X_train['AGE'].mean())
print(X_test['AGE'].isna().sum(),np.var(X_test['AGE']),X_test['AGE'].mean())

38 797.3046136377578 67.04525706010138
12 799.6598214184494 66.4486531986532

In [43]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(strategy='mean')
X_train['AGE']=imputer.fit_transform(X_train[['AGE']])
X_test['AGE']=imputer.transform(X_test[['AGE']])

In [44]:
print(X_train['AGE'].isna().sum())
print(X_test['AGE'].isna().sum())

0
0

In [45]:
X_train['AGE']=mm.fit_transform(X_train[['AGE']])
X_test['AGE']=mm.fit_transform(X_test[['AGE']])
print(X_train['AGE'].mean())
print(X_test['AGE'].mean())

0.6404525706010138
0.6409557498713908

In [46]:
print(X_train['RIVERSIDE'].isna().sum())
print(X_test['RIVERSIDE'].isna().sum())

61
27

In [47]:
most_freq_train=X_train['RIVERSIDE'].mode()[0]
most_freq_test=X_test['RIVERSIDE'].mode()[0]
X_train['RIVERSIDE']=X_train['RIVERSIDE'].fillna(most_freq_train)
X_test['RIVERSIDE']=X_test['RIVERSIDE'].fillna(most_freq_test)
print(X_train['RIVERSIDE'].isna().sum())
print(X_test['RIVERSIDE'].isna().sum())

0
0

In [48]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

pipe=Pipeline([
    ('ohe',OneHotEncoder(sparse_output=False,handle_unknown='ignore').set_output(transform='pandas'))
])
pipe

Pipeline(steps=[('ohe',
                 OneHotEncoder(handle_unknown='ignore', sparse_output=False))])

In [49]:
transformer=ColumnTransformer([
    ('trans',pipe, ['RIVERSIDE']) # Specify 'RIVERSIDE' as the column to transform
],remainder='passthrough',verbose_feature_names_out=False).set_output(transform='pandas')
transformer

ColumnTransformer(remainder='passthrough',
                  transformers=[('trans',
                                 Pipeline(steps=[('ohe',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False))]),
                                 ['RIVERSIDE'])],
                  verbose_feature_names_out=False)

In [50]:
X_train = transformer.fit_transform(X_train)
X_test = transformer.transform(X_test)



```
# other way
ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore').set_output(transform='pandas')
X_train_riverside_ohe = ohe.fit_transform(X_train[['RIVERSIDE']])
X_test_riverside_ohe = ohe.transform(X_test[['RIVERSIDE']])
X_train = pd.concat([X_train.drop('RIVERSIDE', axis=1), X_train_riverside_ohe], axis=1)
X_test = pd.concat([X_test.drop('RIVERSIDE', axis=1), X_test_riverside_ohe], axis=1)
```

In [51]:
X_train.head(2)

,RIVERSIDE_NO,RIVERSIDE_YES,CRIM,ZN,INDUS,POLINDEX,RM,AGE,DIS,HIGHWAYCOUNT,TAX,PTRATIO,IMM,BPL
3336,1.0,0.0,0.189700,0.004561,-0.239852,0.033842,0.428571,0.860000,0.124347,0.192308,0.374853,0.829378,0.989745,0.419050
2540,0.0,1.0,0.036362,0.202330,-0.529958,0.162887,0.571429,0.640453,0.271862,0.115385,0.069331,0.690556,0.976549,0.140763

## Q.13 [5 marks][MCQ] How many features are there after performing above transformation?

Options:

A) 14

B) 15

C) 16

D) 17

E) 18

Ans: A

In [52]:
# Solution
len(X_train.columns)

14

## Q.14 [2 marks][NAT] What is the mean of the transformed test data (features only)?

Note : Compute the mean of the whole feature matrix i.e. mean of all values in the transformed test feature matrix

Ans: 0.38 [Range: 0.33 to 0.43]

In [53]:
# Solution
np.mean(X_test)

np.float64(0.38663239104537866)

---

# Model Building

Load the dataset.

The file has no index column.\
The last column is the target column.\
The first row of the file has column ids

[Click here to view the dataset (V3)](https://drive.google.com/file/d/1OtwemNuw0qilXAutyuZEjOscZVKuD7Tv/view)

In [54]:
path1='/content/drive/MyDrive/Dataset/NPPE1_ModelBuilding3.csv'
raw=pd.read_csv(path1)
raw.head(2)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,0.087472,0.002829,1.768235,0.188396,0.117071,0.148148,0.478165,0.720443,0.967195,0.281563,0.428571,0.959596,1.0,0.0,23.358097
1,0.378379,0.022079,1.115629,0.091974,0.066089,0.851852,0.911759,0.785321,0.885001,0.424648,0.285714,0.868687,0.0,1.0,17.268768

## Split the dataset into train dataset and test dataset in the following manner

Use train_test_split to split the dataset into train and test dataset with test size equal to 0.3(i.e.30%) and random_state equal to 42. Let other parameters have default values.

Columns except the last column should be the feature matrix (X_train or X_test)

Last column will be the label vector.

In [55]:
# Solution
feature=raw.drop('14',axis=1)
label=raw['14'].copy()

In [56]:
X_train,X_test,y_train,y_test=train_test_split(feature,label,random_state=42,test_size=0.3)

## (Common instructions for Q.1, Q.2 and Q.3)

Train the ridge model on the training data with the following parameters:

alpha = 10
solver = 'saga'
tol = 1e-4
random_state = 42

In [57]:
# Solution
from sklearn.linear_model import Ridge
rg=Ridge(alpha=10,solver='saga',tol=1e-4,random_state=42)
rg.fit(X_train,y_train)

Ridge(alpha=10, random_state=42, solver='saga')

## Q1) Enter the value of $R^2$ score on the test dataset.

Ans: 0.66

(Type: Range) 0.656,0.666

In [58]:
from sklearn.metrics import r2_score
rg_pred=rg.predict(X_test)
r2_score(y_test,rg_pred)

0.6613547575262211

## Q2) What is the index of most important feature? Note the index starts from 0. Ignore the intercept for this question.

Ans: 9

In [59]:
# Solution
rg.coef_

array([ -0.4825441 ,   3.74601838,  -0.73583331,   0.54199933,
        -9.89014109,   5.80114296,  -5.06099736,  -9.45015598,
         4.73124885, -23.51321982,  11.31863371,   0.49450664,
        -0.89196134,   0.89196134])

In [60]:
np.argmax(np.abs(rg.coef_))

np.int64(9)

## Q3) What is the index of least important feature? Note the index starts from 0. Ignore the intercept for this question.

Ans: 0

In [61]:
# Solution
np.argmin(np.abs(rg.coef_))

np.int64(0)

## (Common Instructions for Q.4 and Q.5)
Take SGDRegressor(random_state = 42) estimator with GridSearchCV. Hyperparameter tuning to be done over the following parameters:


penalty as ['l1', 'l2']\
alpha values as [1e-5, 1e-4, 1e-3, 1e-2, 1e-1]\
values of tol as [1e-4, 1e-3, 1e-2, 1e-1]\
Use cross-validation = 5\
Set scoring as neg_mean_absolute_error


Use the best model from above hyper parameter tuning process to answer following questions:

In [ ]:
gs=GridSearchCV

In [89]:
# Solution
from sklearn.linear_model import SGDRegressor
from sklearn.model_selection import GridSearchCV
sg=SGDRegressor(random_state=42)
param_grid_sg={
    "penalty":['l1','l2'],
    "alpha": [1e-5, 1e-4, 1e-3, 1e-2, 1e-1],
    "tol":[1e-4, 1e-3, 1e-2, 1e-1],
}
hv=GridSearchCV(sg,param_grid=param_grid_sg,cv=5,scoring='neg_mean_absolute_error',n_jobs=-1)

In [91]:
hv.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=SGDRegressor(random_state=42), n_jobs=-1,
             param_grid={'alpha': [1e-05, 0.0001, 0.001, 0.01, 0.1],
                         'penalty': ['l1', 'l2'],
                         'tol': [0.0001, 0.001, 0.01, 0.1]},
             scoring='neg_mean_absolute_error')

In [95]:
hv.best_params_

{'alpha': 0.001, 'penalty': 'l2', 'tol': 0.0001}

## Q4) What is the best penalty?

> A l1\
> B l2

Ans: B

In [63]:
# Solution

## Q5) What will be value of mean absolute error on the test dataset?

Ans: 3.81

(Type: Range) 3.808,3.818

In [99]:
# Solution
score=-hv.score(X_test,y_test)
score

3.8131121797994014

## (Common Instructions for Q.6 and Q.7)

Create a pipeline of the PCA() as transformer and Lasso as an estimator.


Use GridSearchCV for tuning the hyperparameters of the created pipeline on training dataset.

Values of n_components for PCA to be [0.9, 0.95]\
lasso alpha value to be taken as : [10, 1, 0.01, 0.001]\
scoring : neg_mean_absolute_error.\
Use 5 fold cross validation.\
n_jobs = -1 (negative one) [it helps in using all the computational power to run this job]\
(Note: Kindly ignore the warning.)

In [105]:
from sklearn.decomposition import PCA
from sklearn.linear_model import Lasso
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV

# Create a pipeline with PCA and Lasso
pipeline = Pipeline([
    ('pca', PCA()),
    ('lasso', Lasso())
])

# Define the hyperparameter grid for GridSearchCV
param_grid = {
    'pca__n_components': [0.9, 0.95], # n_components for PCA
    'lasso__alpha': [10, 1, 0.01, 0.001] # alpha for Lasso
}

# Initialize GridSearchCV
grid_search = GridSearchCV(
    pipeline, # The pipeline to tune
    param_grid=param_grid,
    scoring='neg_mean_absolute_error',
    cv=5,
    n_jobs=-1,
    verbose=1
)

# Fit GridSearchCV to the training data
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 8 candidates, totalling 40 fits

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('pca', PCA()), ('lasso', Lasso())]),
             n_jobs=-1,
             param_grid={'lasso__alpha': [10, 1, 0.01, 0.001],
                         'pca__n_components': [0.9, 0.95]},
             scoring='neg_mean_absolute_error', verbose=1)

## Q6)  If we fit the pipeline on the training dataset, what will be the $R^2$ score on the test dataset?

Ans: 0.62

(Type: Range) 0.623,0.633

In [106]:
# Solution
grid_search_pred=grid_search.predict(X_test)
r2_score(y_test,grid_search_pred)

0.6288625430197575

## Q7)  How much variance is explained (Eigen value) by the first principle component?

ANs: 1.16

(Type: Range) 1.158,1.168

In [116]:
# Solution
# Access the best estimator (the fitted pipeline) from GridSearchCV
best_pipeline = grid_search.best_estimator_

# Access the PCA step from the best pipeline
best_pca = best_pipeline.named_steps['pca']

# Get the explained variance of the first principal component
print(best_pca.explained_variance_[0])

1.1635075742239045

In [117]:
grid_search.best_estimator_

Pipeline(steps=[('pca', PCA(n_components=0.95)), ('lasso', Lasso(alpha=0.01))])

In [127]:
grid_search.best_estimator_.named_steps['pca'].explained_variance_

array([1.16350757, 0.15109745, 0.11321585, 0.07019734, 0.03866388,
       0.02770669, 0.02515772])

## Q8) Create a pipeline of the PolynomialFeatures as transformer and Lasso as an estimator with the following parameters:
  - For PolynomialFeatures:
    - interaction_only = False
    - degree = 2
  - For Lasso:
    - alpha = 1
    - warm_start = True
    - random state as 0

Fit the pipeline on the training dataset and find the $R^2$ score on the test dataset.

Ans: 0.15

(Type: Range) 0.152,0.162

In [129]:
# Solution
from sklearn.preprocessing import PolynomialFeatures
pipe_1=Pipeline([
    ('poly',PolynomialFeatures(interaction_only=False,degree=2)),
    ('ls',Lasso(alpha=1,warm_start=True,random_state=0))
])
pipe_1.fit(X_train,y_train)

Pipeline(steps=[('poly', PolynomialFeatures()),
                ('ls', Lasso(alpha=1, random_state=0, warm_start=True))])

In [130]:
pipe_1_pre=pipe_1.predict(X_test)
r2_score(y_test,pipe_1_pre)

0.157678032410551

## Q9) If you eliminate 1 feature with recursive feature elimination, which feature will be eliminated?

Type the index of the eliminated feature (index starts from 0).


Use LinearRegression model with default parameters as an estimator.


Use processed training data.

Ans: 2

In [133]:
# Solution
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression
rf=RFE(LinearRegression())
selector=rf.fit(X_train,y_train)

In [134]:
selector.ranking_ ##best ranking awardwd as 1

array([4, 2, 8, 7, 1, 1, 1, 1, 1, 1, 1, 5, 3, 6])

In [135]:
np.argmax(selector.ranking_)

np.int64(2)

# Few Extra Questions based on New Syllabus

## (Common instructions for Q.1 to Q.5)


Take `DecisionTreeRegressor(criterion='absolute_error', random_state=42)` with `GridSearchCV`. Hyperparameter tuning to be done over the following parameters:


- 'max_depth' as [10, 15, 20, None],
- 'min_samples_split' as [5, 10, 15],
- 'max_features' as ['sqrt', 'log2']
- Use cross validation = 5
- Set scoring as neg_mean_absolute_error
- Set `n_jobs = -1`

### Q1) What is the best `max_depth`?

In [137]:
# Solution
from sklearn.tree import DecisionTreeRegressor
dt=DecisionTreeRegressor(criterion='absolute_error',random_state=42)
param_grid={
    "max_depth":[10, 15, 20, None],
    "min_samples_split":[5,10,15],
    "max_features":['sqrt','log2'],
}
gs=GridSearchCV(dt,param_grid=param_grid,cv=5,scoring='neg_mean_absolute_error',n_jobs=-1)

In [139]:
gs.fit(X_train,y_train)

GridSearchCV(cv=5,
             estimator=DecisionTreeRegressor(criterion='absolute_error',
                                             random_state=42),
             n_jobs=-1,
             param_grid={'max_depth': [10, 15, 20, None],
                         'max_features': ['sqrt', 'log2'],
                         'min_samples_split': [5, 10, 15]},
             scoring='neg_mean_absolute_error')

In [148]:
gs.best_params_

{'max_depth': None, 'max_features': 'sqrt', 'min_samples_split': 5}

### Q2) Using the best estimator, find the $R^2$ score on the test dataset

In [149]:
# Solution
gs_pred=gs.predict(X_test)
r2_score(y_test,gs_pred)

0.7768079393414741

### Q3) What is the height of the best tree?

In [72]:
# Solution

### Q4) How many nodes are there in the best tree?

In [155]:
# Solution
gs.best_estimator_.tree_.node_count

2541

### Q5) What is the absoluete error (impurity) at the root node?

In [156]:
# Solution
gs.best_estimator_.tree_.impurity[0]

np.float64(6.1782382365535415)

## (Common instructions for Q.6 to Q.7)

Train the support vector regressor on the training data with the following parameters

- kernel = 'poly'
- degree = 3
- C = 0.1

### Q6) What is the root mean sqaured error on the test dataset?

In [158]:
# Solution
from sklearn.svm import SVR
sv=SVR(kernel='poly',degree=3,C=0.1)
sv.fit(X_train,y_train)

SVR(C=0.1, kernel='poly')

In [160]:
from sklearn.metrics import root_mean_squared_error
sv_pred=sv.predict(X_test)
root_mean_squared_error(y_test,sv_pred)

5.763033357080082

### Q7) How many support vectors are there?

In [163]:
# Solution
sv.n_support_

array([2720], dtype=int32)

### Q8)  Tune the parameters using Gridsearchcv for below settings  

- `estimator = KNeighborsRegressor`
- `scoring = neg_mean_squared_error`
- `cv= 5`
* Consider following parameters for KNeighborsRegressor:
 - `n_neighbors = [11,17,23,29]`
 - `metric = "minkowski"`
 - Set p value for `minkowski = 2`

- Keep other parameter values as default values.

### What is the best value of K you obtained using the above instructions?

In [169]:
# Solution
from sklearn.model_selection import RandomizedSearchCV
from sklearn.neighbors import KNeighborsRegressor
knn=KNeighborsRegressor()
param_grid={
    "n_neighbors":[11,17,23,29],
    "metric" : ["minkowski"],
    "p":[2]
}
rs=RandomizedSearchCV(knn,cv=5,param_distributions=param_grid,scoring='neg_mean_squared_error',n_jobs=-1)
rs.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_search.py:317: UserWarning: The total space of parameters 4 is smaller than n_iter=10. Running 4 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

RandomizedSearchCV(cv=5, estimator=KNeighborsRegressor(), n_jobs=-1,
                   param_distributions={'metric': ['minkowski'],
                                        'n_neighbors': [11, 17, 23, 29],
                                        'p': [2]},
                   scoring='neg_mean_squared_error')

In [173]:
rs.best_params_['n_neighbors']

11

### Q9) Train  with RandomizedSearchCV.

- Keep Below Settings for **`RandomForestRegressor(random_state=42)`** estimator
  - n_estimators = range(2,100)
  - max_depth = range(1,11)
  - min_impurity_decrease = uniform(loc=0,scale=5)


- Keep below settings for RandomizedSearchCV
  - estimator = RandomForestClassifier(random_state=42)
  - random_state = 42
  - n_iter=5
  - cv=3
  - n_jobs= -1
  - verbose=2

hint: from scipy.stats import uniform

Submit the best param value for n_estimators using this RandomizedSearchCV on train data.

In [179]:
# Solution
from sklearn.ensemble import RandomForestRegressor
from scipy.stats import uniform # Import uniform from scipy.stats

rf=RandomForestRegressor(random_state=42)
param_grid={
    "n_estimators":range(2,100), # Corrected parameter name from n_neighbors to n_estimators
    "max_depth":range(1,11),
    "min_impurity_decrease":uniform(loc=0,scale=5) # Corrected to use scipy.stats.uniform
}
rs=RandomizedSearchCV(rf,random_state=42,param_distributions=param_grid,n_iter=5,cv=3,n_jobs=-1,verbose=2)
rs.fit(X_train,y_train)

Fitting 3 folds for each of 5 candidates, totalling 15 fits

RandomizedSearchCV(cv=3, estimator=RandomForestRegressor(random_state=42),
                   n_iter=5, n_jobs=-1,
                   param_distributions={'max_depth': range(1, 11),
                                        'min_impurity_decrease': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x7cc2b1c10200>,
                                        'n_estimators': range(2, 100)},
                   random_state=42, verbose=2)

In [180]:
rs.best_estimator_

RandomForestRegressor(max_depth=7,
                      min_impurity_decrease=np.float64(0.2904180608409973),
                      n_estimators=89, random_state=42)

### Q10) Train `AdaBoostRegressor` with

*  `random_state=42`
* `n_estimators=200`
* `loss='square'`

Using impurity-based feature importances, what is the highest feature importance score?

In [181]:
# Solution
from sklearn.ensemble import AdaBoostRegressor
ada=AdaBoostRegressor(n_estimators=200,random_state=42,loss='square')
ada.fit(X_train,y_train)

AdaBoostRegressor(loss='square', n_estimators=200, random_state=42)

In [183]:
ada.feature_importances_.max()

np.float64(0.38108141326752737)

### Q11) Train `BaggingRegressor` with

* `n_estimators=100`,
* `max_features=0.7`,
* `oob_score=True`,
* `random_state=42`

What is the out of bag score?

In [185]:
# Solution
from sklearn.ensemble import  BaggingRegressor
bg=BaggingRegressor(n_estimators=100,max_features=0.7,oob_score=True,random_state=42)
bg.fit(X_train,y_train)

BaggingRegressor(max_features=0.7, n_estimators=100, oob_score=True,
                 random_state=42)

In [189]:
bg.oob_score_

0.9034784429606962

## (Common instructions for Q.12 to Q.13)

Train a `MLPRegressor(random_state=42, hidden_layer_sizes=(20, 20), solver='sgd')` model and tune the below parameters using `GridSearchCV`

*   'activation' for the values ['logistic', 'tanh', 'relu'],
* 'learning_rate_init' for the values [0.001, 0.01, 0.1]

### Q12) What is the number of iteration the solver has run for the best model?

In [191]:
# Solution
from sklearn.neural_network import MLPRegressor
ml=MLPRegressor(random_state=42, hidden_layer_sizes=(20, 20), solver='sgd')
param_grid={
    'activation':['logistic', 'tanh', 'relu'],
    "learning_rate_init":[0.001, 0.01, 0.1]
}
gs=GridSearchCV(ml,param_grid=param_grid,n_jobs=-1)
gs.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

GridSearchCV(estimator=MLPRegressor(hidden_layer_sizes=(20, 20),
                                    random_state=42, solver='sgd'),
             n_jobs=-1,
             param_grid={'activation': ['logistic', 'tanh', 'relu'],
                         'learning_rate_init': [0.001, 0.01, 0.1]})

In [195]:
gs.

MLPRegressor(hidden_layer_sizes=(20, 20), random_state=42, solver='sgd')

In [197]:
gs.best_estimator_.n_iter_

200

### Q13) What is the bias at the output layer for the best model?

In [200]:
# Solution
gs.best_estimator_.

'tanh'

In [201]:
gs.best_estimator_.intercepts_[-1]

array([3.1006592])